
-- tables

CREATE TABLE USER(
     ID INT NOT NULL  ,
     NAME VARCHAR( 50 ) NOT NULL ,
     DESCRIPTION VARCHAR (50),
     EMAIL VARCHAR(50) NOT NULL,
     CREATED_BY VARCHAR(50),
     CREATED_DATE TIMESTAMP,
     UPDATED_BY VARCHAR(50),
     UPDATED_DATE TIMESTAMP,
     ENABLED CHAR(1) DEFAULT 'Y',
     PRIMARY KEY (`ID`)
);

CREATE TABLE ITEM(
     ID INT NOT NULL AUTO_INCREMENT ,
     NAME VARCHAR( 50 ) NOT NULL ,
     DESCRIPTION VARCHAR (50),
     USER_ID INT,
     CREATED_BY VARCHAR(50),
     CREATED_DATE TIMESTAMP,
     UPDATED_BY VARCHAR(50),
     UPDATED_DATE TIMESTAMP,
     ENABLED CHAR(1) DEFAULT 'Y',
     PRIMARY KEY (`ID`),
     KEY `ITEM_USER_FK` (`USER_ID`),
     CONSTRAINT `ITEM_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
);

-- Sample data

INSERT INTO `USER`
(ID, NAME, DESCRIPTION, EMAIL, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, ENABLED)
VALUES(1, 'Amy', 'Test User 1', 'amy@mail.com', 'SYSTEM', UTC_TIMESTAMP, NULL, NULL, 'Y');

INSERT INTO `USER`
(ID, NAME, DESCRIPTION, EMAIL, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, ENABLED)
VALUES(2, 'Bob', 'Test User 2', 'bob@mail.com', 'SYSTEM', UTC_TIMESTAMP, NULL, NULL, 'Y');

INSERT INTO `ITEM`
(ID, NAME, DESCRIPTION, USER_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, ENABLED)
VALUES(1, 'Laptop', 'Amy''s Laptop', 1, 'SYSTEM', UTC_TIMESTAMP, NULL, NULL, 'Y');

INSERT INTO `ITEM`
(ID, NAME, DESCRIPTION, USER_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, ENABLED)
VALUES(2, 'Laptop', 'Bob''s Laptop', 2, 'SYSTEM', UTC_TIMESTAMP, NULL, NULL, 'Y');

INSERT INTO `ITEM`
(ID, NAME, DESCRIPTION, USER_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, ENABLED)
VALUES(3, 'Mouse', 'Bob''s Mouse', 2, 'SYSTEM', UTC_TIMESTAMP, NULL, NULL, 'Y');

-- Stored Procedure

CREATE PROCEDURE P_ITEM_ENABLED_BY_USER(IN PARAM_USER_ID INT)
   BEGIN
   SELECT *  FROM ITEM 
   WHERE ENABLED = 'Y' AND USER_ID = PARAM_USER_ID;
   END